import type { AppDef } from "./window-manager";
import {
  AboutIcon,
  SkillsIcon,
  ExperienceIcon,
  ProjectsIcon,
  ContactIcon,
  CVIcon,
  TerminalIcon,
  SettingsIcon,
  SudokuIcon,
  SnakeIcon,
  GalleryIcon,
  MusicIcon,
  TrashIcon,
  WelcomeIcon,
  BrowserIcon,
} from "./app-icons";

export const apps: Record<
  AppDef["id"],
  AppDef & { icon: React.ReactNode }
> = {
  about: {
    id: "about",
    title: "About Me",
    iconKey: "user",
    icon: <AboutIcon />,
    defaultSize: { width: 760, height: 600 },
    resizable: true,
    singleton: true,
  },
  skills: {
    id: "skills",
    title: "Skills",
    iconKey: "code",
    icon: <SkillsIcon />,
    defaultSize: { width: 820, height: 620 },
    resizable: true,
    singleton: true,
  },
  experience: {
    id: "experience",
    title: "Experience",
    iconKey: "briefcase",
    icon: <ExperienceIcon />,
    defaultSize: { width: 780, height: 620 },
    resizable: true,
    singleton: true,
  },
  projects: {
    id: "projects",
    title: "Projects",
    iconKey: "folder",
    icon: <ProjectsIcon />,
    defaultSize: { width: 880, height: 640 },
    resizable: true,
    singleton: true,
  },
  contact: {
    id: "contact",
    title: "Contact",
    iconKey: "envelope",
    icon: <ContactIcon />,
    defaultSize: { width: 760, height: 520 },
    resizable: true,
    singleton: true,
  },
  cv: {
    id: "cv",
    title: "Resume.pdf",
    iconKey: "pdf",
    icon: <CVIcon />,
    defaultSize: { width: 820, height: 700 },
    resizable: true,
    singleton: true,
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    iconKey: "terminal",
    icon: <TerminalIcon />,
    defaultSize: { width: 720, height: 460 },
    resizable: true,
    singleton: true,
  },
  settings: {
    id: "settings",
    title: "Settings",
    iconKey: "cog",
    icon: <SettingsIcon />,
    defaultSize: { width: 600, height: 480 },
    resizable: true,
    singleton: true,
  },
  sudoku: {
    id: "sudoku",
    title: "Sudoku",
    iconKey: "sudoku",
    icon: <SudokuIcon />,
    defaultSize: { width: 560, height: 640 },
    resizable: false,
    singleton: true,
  },
  snake: {
    id: "snake",
    title: "Snake",
    iconKey: "snake",
    icon: <SnakeIcon />,
    defaultSize: { width: 560, height: 640 },
    resizable: false,
    singleton: true,
  },
  gallery: {
    id: "gallery",
    title: "Gallery",
    iconKey: "gallery",
    icon: <GalleryIcon />,
    defaultSize: { width: 820, height: 600 },
    resizable: true,
    singleton: true,
  },
  music: {
    id: "music",
    title: "Music",
    iconKey: "music",
    icon: <MusicIcon />,
    defaultSize: { width: 880, height: 640 },
    resizable: true,
    singleton: true,
  },
  trash: {
    id: "trash",
    title: "Trash",
    iconKey: "trash",
    icon: <TrashIcon />,
    defaultSize: { width: 640, height: 500 },
    resizable: true,
    singleton: true,
  },
  welcome: {
    id: "welcome",
    title: "Welcome",
    iconKey: "welcome",
    icon: <WelcomeIcon />,
    defaultSize: { width: 660, height: 560 },
    resizable: true,
    singleton: true,
  },
  browser: {
    id: "browser",
    title: "Browser",
    iconKey: "browser",
    icon: <BrowserIcon />,
    defaultSize: { width: 960, height: 680 },
    resizable: true,
    singleton: true,
  },
};
